### ISSUE TITLE
Set Repo as Fork of Chris Aldridge Work?

### ISSUE THREAD

**Issue by JosephAllen** [GSA/sf-trigger-framework#6]
Should we consider setting a remote for this repo to reference that is a fork of [Chris Aldridge](https://github.com/ChrisAldridge/Lightweight-Trigger-Framework) original work?

[Directions for Configuring a remote for a fork
](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork)

**Comment by rdugarSFDC** [comment]
Yes we can  do that.

**Comment by mvogelgesang** [comment]
@JosephAllen thanks for calling this out. I have created a fork of Chris' repo and it is available at https://github.com/GSA/Lightweight-Trigger-Framework. I have also placed any of @rdugar-agiledev code changes on top of the current fork and attributed those back to him. I will be deleting this repository so as to avoid any confusion with the new one.
