### ISSUE TITLE
Remove Chris Aldrige Blog Content from README

### ISSUE THREAD

**Issue by JosephAllen** [GSA/sf-trigger-framework#8]
@rdugar-agiledev 

The README has a ton of content that was copied word for word from the Chris Aldridge technical blog [Lightweight Apex Trigger Framework](http://chrisaldridge.com/triggers/lightweight-apex-trigger-framework/), published December 31, 2015. Chris has been kind enough to [share the code](https://github.com/ChrisAldridge/Lightweight-Trigger-Framework) under MIT, but the blog post text is another story.

Major portions of the README are using someone else's copy protected work.

Forking code under MIT  === OK
Copying text from a blog post !== :-(

**Comment by rdugarSFDC** [comment]
Agreed, the original intent was for GSA dev teams to reference this directly, I have updated the README to remove everything which was from Chris's blog post. Let me know if you still have concerns.
